In [1]:
pip install psycopg2

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
from pathlib import Path
from collections import Counter

In [59]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
import json
import pandas as pd
import numpy as np
import joblib
from sqlalchemy import create_engine
import psycopg2

from config import db_password

import time

In [5]:
db_string = f"postgresql://postgres:{db_password}@database-1.caguabqj2yzf.us-east-2.rds.amazonaws.com/3rdDown"

In [6]:
engine = create_engine(db_string)

In [7]:
df = pd.read_sql('''SELECT * FROM "PlayAws"''', con=engine)

In [8]:
df

PlayId      GameId  Quarter  Minute  Second OffenseTeam DefenseTeam  \
0           2  2020122602        2       9      44          LV         MIA   
1           3  2020122602        2       9       3          LV         MIA   
2           4  2020122500        3       1      17         MIN          NO   
3           5  2020122500        3       1      12         MIN          NO   
4           6  2020122500        3       1       6         MIN          NO   
...       ...         ...      ...     ...     ...         ...         ...   
46184   46186  2020091300        4       1      38         ATL         SEA   
46185   46187  2020091300        4       5      18                           
46186   46188  2020091300        4       2       0         ATL         SEA   
46187   46189  2020091300        4       2       0                           
46188   46190  2020091300        4       2      16         ATL         SEA   

       Down  ToGo  Yards  ...  IsTwoPointConversion  \
0         2    10     -9  ...                     0   
1         3    19     18  ...                     0   
2         3     9      0  ...                     0   
3         1    10      0  ...                     0   
4         1     1     -3  ...                     0   
...     ...   ...    ...  ...                   ...   
46184     2     9      2  ...                     0   
46185     0     0      0  ...                     0   
46186     1    10      1  ...                     0   
46187     0     0      0  ...                     0   
46188     1    10     12  ...                     0   

      IsTwoPointConversionSuccessful  RushDirection YardLineFixed  \
0                                  0                           18   
1                                  0     LEFT GUARD            27   
2                                  0                           33   
3                                  0                           18   
4                                  0     LEFT GUARD             1   
...                              ...            ...           ...   
46184                              0                           20   
46185                              0                            0   
46186                              0                           21   
46187                              0                            0   
46188                              0                           33   

       YardLineDirection IsPenaltyAccepted PenaltyTeam  IsNoPlay  \
0                    OPP                 0                     0   
1                    OPP                 0                     0   
2                    OPP                 0          NO         1   
3                    OPP                 1          NO         1   
4                    OPP                 0                     0   
...                  ...               ...         ...       ...   
46184                OPP                 0                     0   
46185                OPP                 0                     0   
46186                OPP                 0                     0   
46187                OPP                 0                     0   
46188                OPP                 0                     0   

                       PenaltyType PenaltyYards  
0                                             0  
1                                             0  
2                DEFENSIVE HOLDING            0  
3      DEFENSIVE PASS INTERFERENCE           17  
4                                             0  
...                            ...          ...  
46184                                         0  
46185                                         0  
46186                                         0  
46187                                         0  
46188                                         0  

[46189 rows x 42 columns]

In [9]:
df.columns

Index(['PlayId', 'GameId', 'Quarter', 'Minute', 'Second', 'OffenseTeam',
       'DefenseTeam', 'Down', 'ToGo', 'Yards', 'YardsPlusMinus',
       'Successful3rdDown', 'YardLine', 'SeriesFirstDown', 'NextScore',
       'Description', 'TeamWin', 'SeasonYear', 'Formation', 'PlayType',
       'IsRush', 'IsPass', 'IsIncomplete', 'IsTouchdown', 'PassType', 'IsSack',
       'IsChallenge', 'IsChallengeReversed', 'IsMeasurement', 'IsInterception',
       'IsFumble', 'IsPenalty', 'IsTwoPointConversion',
       'IsTwoPointConversionSuccessful', 'RushDirection', 'YardLineFixed',
       'YardLineDirection', 'IsPenaltyAccepted', 'PenaltyTeam', 'IsNoPlay',
       'PenaltyType', 'PenaltyYards'],
      dtype='object')

In [10]:

df["OffenseTeam"].unique()

array(['LV', 'MIN', 'TB', 'ARI', 'DEN', 'MIA', '', 'NYJ', 'CLE', 'NYG',
       'BAL', 'CIN', 'HOU', 'CHI', 'IND', 'PIT', 'DAL', 'WAS', 'SEA',
       'LA', 'CAR', 'TEN', 'BUF', 'KC', 'GB', 'ATL', 'NE', 'JAX', 'SF',
       'LAC', 'PHI', 'DET', 'NO'], dtype=object)

In [11]:
#Keep
df = df[['Quarter', 'Down' , 'ToGo', 'Successful3rdDown' , 'Formation','PlayType',]]
df.head()

Quarter  Down  ToGo Successful3rdDown     Formation PlayType
0        2     2    10          4th Down       SHOTGUN     SACK
1        2     3    19          4th Down       SHOTGUN     RUSH
2        3     3     9          4th Down       SHOTGUN     PASS
3        3     1    10          4th Down  UNDER CENTER     PASS
4        3     1     1          4th Down  UNDER CENTER     RUSH

In [12]:
df.isna().sum()

Quarter              0
Down                 0
ToGo                 0
Successful3rdDown    0
Formation            0
PlayType             0
dtype: int64

In [13]:
df[["Formation", "PlayType"]] = \
    df[["Formation", "PlayType"]].fillna("unk")

In [14]:
df.isna().sum()

Quarter              0
Down                 0
ToGo                 0
Successful3rdDown    0
Formation            0
PlayType             0
dtype: int64

In [15]:
#Drop all null values
df = df.dropna()
df.head()

Quarter  Down  ToGo Successful3rdDown     Formation PlayType
0        2     2    10          4th Down       SHOTGUN     SACK
1        2     3    19          4th Down       SHOTGUN     RUSH
2        3     3     9          4th Down       SHOTGUN     PASS
3        3     1    10          4th Down  UNDER CENTER     PASS
4        3     1     1          4th Down  UNDER CENTER     RUSH

In [16]:
# Get list of unique play types
df['PlayType'].unique().tolist()

['SACK',
 'RUSH',
 'PASS',
 'NO PLAY',
 'FIELD GOAL',
 'TIMEOUT',
 '',
 'PUNT',
 'SCRAMBLE',
 'EXTRA POINT',
 'QB KNEEL',
 'TWO-POINT CONVERSION',
 'FUMBLES',
 'CLOCK STOP',
 'KICK OFF',
 'EXCEPTION',
 'PENALTY']

In [17]:
# create list of playtypes resulting in actual play
playlist=df['PlayType'].unique().tolist()
playlist2=['PASS','RUSH','FUMBLE','SACK','SCRAMBLE']

In [18]:
# created new dataframe using loc method to retrieve Quarter 4, 3rd Down, and unique play typles
q4_df=\
df.loc[(df['Quarter']==4)&\
       (df['Down']== 3)&\
      (df['PlayType'].isin(playlist2))\
      ].reset_index()

In [19]:
# Get count of play types
q4_df['PlayType'].value_counts()

PASS        1192
RUSH         434
SACK         137
SCRAMBLE      74
Name: PlayType, dtype: int64

In [20]:
q4_df

index  Quarter  Down  ToGo Successful3rdDown          Formation PlayType
0        11        4     3    10                 N            SHOTGUN     PASS
1        25        4     3     2                 Y       UNDER CENTER     RUSH
2        32        4     3     3                 Y            SHOTGUN     RUSH
3        55        4     3     7                 N            SHOTGUN     PASS
4        67        4     3    10                 N            SHOTGUN     PASS
...     ...      ...   ...   ...               ...                ...      ...
1832  45977        4     3     3                 Y            SHOTGUN     PASS
1833  45984        4     3     9                 N            SHOTGUN     PASS
1834  45993        4     3    19                 N            SHOTGUN     PASS
1835  46090        4     3     1                 N            SHOTGUN     RUSH
1836  46183        4     3     7                 Y  NO HUDDLE SHOTGUN     PASS

[1837 rows x 7 columns]

In [21]:
# Use loc method to retrieve columns form dataframe
q4_df2 = q4_df.loc[:,"ToGo":"PlayType"]
q4_df2

ToGo Successful3rdDown          Formation PlayType
0       10                 N            SHOTGUN     PASS
1        2                 Y       UNDER CENTER     RUSH
2        3                 Y            SHOTGUN     RUSH
3        7                 N            SHOTGUN     PASS
4       10                 N            SHOTGUN     PASS
...    ...               ...                ...      ...
1832     3                 Y            SHOTGUN     PASS
1833     9                 N            SHOTGUN     PASS
1834    19                 N            SHOTGUN     PASS
1835     1                 N            SHOTGUN     RUSH
1836     7                 Y  NO HUDDLE SHOTGUN     PASS

[1837 rows x 4 columns]

# Split Data into Training and Testing

In [22]:
# Create our features
y = q4_df2["Successful3rdDown"]
X = q4_df2.drop("Successful3rdDown", axis=1)
X = pd.get_dummies(X)

In [23]:
# Create our target
y = y.replace({"N":0, "Y":1})
y.value_counts()

0    1091
1     746
Name: Successful3rdDown, dtype: int64

In [24]:
X.describe()

ToGo  Formation_NO HUDDLE  Formation_NO HUDDLE SHOTGUN  \
count  1837.000000          1837.000000                  1837.000000   
mean      6.880240             0.009799                     0.085465   
std       5.152133             0.098528                     0.279649   
min       1.000000             0.000000                     0.000000   
25%       3.000000             0.000000                     0.000000   
50%       6.000000             0.000000                     0.000000   
75%      10.000000             0.000000                     0.000000   
max      34.000000             1.000000                     1.000000   

       Formation_SHOTGUN  Formation_UNDER CENTER  PlayType_PASS  \
count        1837.000000             1837.000000    1837.000000   
mean            0.765378                0.139358       0.648884   
std             0.423878                0.346414       0.477449   
min             0.000000                0.000000       0.000000   
25%             1.000000                0.000000       0.000000   
50%             1.000000                0.000000       1.000000   
75%             1.000000                0.000000       1.000000   
max             1.000000                1.000000       1.000000   

       PlayType_RUSH  PlayType_SACK  PlayType_SCRAMBLE  
count    1837.000000    1837.000000        1837.000000  
mean        0.236255       0.074578           0.040283  
std         0.424896       0.262781           0.196676  
min         0.000000       0.000000           0.000000  
25%         0.000000       0.000000           0.000000  
50%         0.000000       0.000000           0.000000  
75%         0.000000       0.000000           0.000000  
max         1.000000       1.000000           1.000000

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [26]:
X_train

ToGo  Formation_NO HUDDLE  Formation_NO HUDDLE SHOTGUN  \
812      5                    0                            1   
1388     9                    0                            0   
1205     2                    0                            0   
1282     4                    0                            0   
957      6                    0                            0   
...    ...                  ...                          ...   
905      6                    0                            0   
1791     7                    0                            0   
1096     3                    0                            0   
235      9                    0                            0   
1061     7                    0                            0   

      Formation_SHOTGUN  Formation_UNDER CENTER  PlayType_PASS  PlayType_RUSH  \
812                   0                       0              1              0   
1388                  1                       0              1              0   
1205                  0                       1              0              1   
1282                  1                       0              1              0   
957                   1                       0              1              0   
...                 ...                     ...            ...            ...   
905                   1                       0              1              0   
1791                  1                       0              1              0   
1096                  1                       0              1              0   
235                   1                       0              1              0   
1061                  1                       0              1              0   

      PlayType_SACK  PlayType_SCRAMBLE  
812               0                  0  
1388              0                  0  
1205              0                  0  
1282              0                  0  
957               0                  0  
...             ...                ...  
905               0                  0  
1791              0                  0  
1096              0                  0  
235               0                  0  
1061              0                  0  

[1377 rows x 9 columns]

In [27]:
X_test

ToGo  Formation_NO HUDDLE  Formation_NO HUDDLE SHOTGUN  \
556      7                    0                            0   
1406     1                    0                            0   
1451     4                    0                            0   
111      1                    0                            1   
1788     1                    0                            0   
...    ...                  ...                          ...   
1047     4                    0                            0   
1615    11                    0                            0   
1092    10                    0                            1   
1493     9                    0                            0   
1724    11                    0                            1   

      Formation_SHOTGUN  Formation_UNDER CENTER  PlayType_PASS  PlayType_RUSH  \
556                   1                       0              1              0   
1406                  0                       1              0              1   
1451                  1                       0              0              0   
111                   0                       0              0              1   
1788                  1                       0              0              1   
...                 ...                     ...            ...            ...   
1047                  1                       0              1              0   
1615                  0                       1              0              1   
1092                  0                       0              1              0   
1493                  1                       0              1              0   
1724                  0                       0              1              0   

      PlayType_SACK  PlayType_SCRAMBLE  
556               0                  0  
1406              0                  0  
1451              1                  0  
111               0                  0  
1788              0                  0  
...             ...                ...  
1047              0                  0  
1615              0                  0  
1092              0                  0  
1493              0                  0  
1724              0                  0  

[460 rows x 9 columns]

# Logistic Regression (Binary Classification)

In [28]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier

LogisticRegression(random_state=1)

In [29]:
# Train the data
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [30]:
# Make Predictions
predictions = classifier.predict(X_test)

In [31]:
classifier.predict(X_test)

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,

In [32]:
classifier.predict_proba(X_test)

array([[0.58942557, 0.41057443],
       [0.39193759, 0.60806241],
       [0.95880245, 0.04119755],
       [0.35006864, 0.64993136],
       [0.40496071, 0.59503929],
       [0.49007617, 0.50992383],
       [0.5348054 , 0.4651946 ],
       [0.54839789, 0.45160211],
       [0.39193759, 0.60806241],
       [0.54839789, 0.45160211],
       [0.54839789, 0.45160211],
       [0.39193759, 0.60806241],
       [0.34462325, 0.65537675],
       [0.39721924, 0.60278076],
       [0.39193759, 0.60806241],
       [0.62924584, 0.37075416],
       [0.40745803, 0.59254197],
       [0.42360904, 0.57639096],
       [0.95880245, 0.04119755],
       [0.59815492, 0.40184508],
       [0.42360904, 0.57639096],
       [0.54839789, 0.45160211],
       [0.62924584, 0.37075416],
       [0.46491186, 0.53508814],
       [0.70344689, 0.29655311],
       [0.38334677, 0.61665323],
       [0.38205582, 0.61794418],
       [0.3324564 , 0.6675436 ],
       [0.46491186, 0.53508814],
       [0.42360904, 0.57639096],
       [0.

In [33]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print ("Accuracy score")
print (accuracy_score(y_test, predictions))

Accuracy score
0.6826086956521739


In [34]:
# Display the confusion matrix
# Calculating the confusion matrix.
cm = confusion_matrix(y_test,predictions)

# Create a DataFrame from the confusion matrix.
cm_df= pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [35]:
#from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# Displaying results
print("Confusion Matrix")
display(cm_df)
#print(f"Accuracy Score : {accuracy_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          204           67
Actual 1           79          110

Classification Report
              precision    recall  f1-score   support

           0       0.72      0.75      0.74       271
           1       0.62      0.58      0.60       189

    accuracy                           0.68       460
   macro avg       0.67      0.67      0.67       460
weighted avg       0.68      0.68      0.68       460



In [36]:
#save model in output directory
joblib.dump(classifier,'classifier.pkl')

['classifier.pkl']

### Predict with new data

In [37]:
import numpy as np

test_data = []
#convert test_data into numpy array
test_data = np.array(test_data)
#reshape
test_data = test_data.reshape(1,-1)
print(test_data)

[[5.1 3.2 1.5 0.4 8.3 3.9 5.  9.8 6.8]]


### Load trained model

In [38]:
#declare path where you saved your model
outFileFolder = ''
filePath = outFileFolder + 'classifier.pkl'
#open file
file = open(filePath, "rb")
#load the trained model
trained_model = joblib.load(file)

### Predict with trained model

In [39]:
prediction = trained_model.predict(test_data)
print(prediction)

[0]


In [46]:
import numpy as np

test_data = pd.DataFrame(

{
    "ToGo":[2],
    "Formation_NO HUDDLE":[0],
    "Formation_NO HUDDLE SHOTGUN":[0],
    "Formation_SHOTGUN":[1],
    "Formation_UNDER CENTER":[0],    
    "PlayType_PASS":[0],
    "PlayType_RUSH":[1],
    "PlayType_SACK":[0],
    "PlayType_SCRAMBLE":[0]
})
#convert test_data into numpy array
#test_data = np.array(test_data)
#reshape
#test_data = test_data.reshape(1,-1)
display(test_data)

ToGo  Formation_NO HUDDLE  Formation_NO HUDDLE SHOTGUN  Formation_SHOTGUN  \
0     2                    0                            0                  1   

   Formation_UNDER CENTER  PlayType_PASS  PlayType_RUSH  PlayType_SACK  \
0                       0              0              1              0   

   PlayType_SCRAMBLE  
0                  0

ToGo  Formation_NO HUDDLE  Formation_NO HUDDLE SHOTGUN  \
556     7                    0                            0   

     Formation_SHOTGUN  Formation_UNDER CENTER  PlayType_PASS  PlayType_RUSH  \
556                  1                       0              1              0   

     PlayType_SACK  PlayType_SCRAMBLE  
556              0                  0

In [43]:
X_test.columns


Index(['ToGo', 'Formation_NO HUDDLE', 'Formation_NO HUDDLE SHOTGUN',
       'Formation_SHOTGUN', 'Formation_UNDER CENTER', 'PlayType_PASS',
       'PlayType_RUSH', 'PlayType_SACK', 'PlayType_SCRAMBLE'],
      dtype='object')

In [47]:
trained_model.predict(test_data)

array([1])

In [53]:
test_data.iloc[0].values

array([2, 0, 0, 1, 0, 0, 1, 0, 0])

In [58]:
trained_model.predict(np.array(test_data.iloc[0].values).reshape(-1,9))

array([1])